### ISSUE TITLE
Improvements to the GitHub Community Standards

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-mobile#1]
This issue involves researching and implementing the standards required for open-source applications in the GitHub Community Standards.

Progress tracking is done through the following link:
https://github.com/afet-yonetim-sistemi/ays-mobile/community

---

**Resources:**
- https://opensource.guide
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories

**Comment by rasitcolakel** [comment]
Gerekli dosyalar eklendi 💯

**Comment by agitrubard** [comment]
@rasitcolakel issue done yapılmış ama branch protection gibi şeyler yapılmamış, tekrardan gözden geçirebilir miyiz?

**Comment by rasitcolakel** [comment]
> @rasitcolakel issue done yapılmış ama branch protection gibi şeyler yapılmamış, tekrardan gözden geçirebilir miyiz?

Tamamlandı 🚀
