### ISSUE TITLE
Uygulama Dilinin Telefonda Kullanılan Dil Bilgisi İle Senkronize Olması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-mobile#4]
Bu issue ile birlikte uygulamanın kullandığı dil, telefonda hâli hazırda kullanılan dil ile aynı olması sağlanmalı ve dil değiştiğinde uygulamanın da buna uygun olarak hareket etmesi gerekmektedir.

**Comment by rasitcolakel** [comment]
Bu issue c13ba94 commiti ile tamamlanmıştır. Ek olarak kullanıcı isterse ayarlar ekranından dilini değiştirebilmekte 👍

**Comment by agitrubard** [comment]
@rasitcolakel eline sağlık 🙌🏼  Burada da pull reuqestler ile ilerleyebilir miyiz?
